# Generated by Django 4.2.4 on 2023-08-31 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='chess',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='chess',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chess',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chess_friends.category'),
        ),
        migrations.AlterField(
            model_name='chess',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chess',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chess',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chess',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chess',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
